### ISSUE TITLE
Test the bot in x86

### ISSUE THREAD

**Issue by Smim0** [filirnd/owbot#3]
Hi,

I would like to test the bot in a VM but I am a bit confused on how to compile it, I would apreciate your help.

Thanks

**Comment by filirnd** [comment]
Hi, yes I didn't describe the compile steps because I need to test it yet a little time. But if you want to compile in a VM you must clone the project, go into project directory and use 
`go build -o owbot cmd/main.go` 
command as an generic go program. 
If you see some weird option on Makefile is because that compile commands was used for a cross-compiling for specific cpu architecture.
Remember that if you don't use a openwrt distro on vm, the "clients" command can be not valid/not working.

If you have some other question feel free to ask!

**Comment by Smim0** [comment]
In the Makefile I can change the GOARCH to amd64 but I still have some error messages when I try to compile

`cmd/main.go:8:2: cannot find package "github.com/filirnd/owbot/functions" in any of:
	/usr/lib/go-1.6/src/github.com/filirnd/owbot/functions (from $GOROOT)
	($GOPATH not set)
cmd/main.go:9:2: cannot find package "github.com/filirnd/owbot/models/config" in any of:
	/usr/lib/go-1.6/src/github.com/filirnd/owbot/models/config (from $GOROOT)
	($GOPATH not set)
cmd/main.go:10:2: cannot find package "github.com/filirnd/owbot/models/telegram" in any of:
	/usr/lib/go-1.6/src/github.com/filirnd/owbot/models/telegram (from $GOROOT)
	($GOPATH not set)`

**Comment by filirnd** [comment]
Have you $GOPATH set on your system path ?

**Comment by filirnd** [comment]
No more info about. Closing the issue.
